version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: chemical_db
    environment:
      MYSQL_ROOT_PASSWORD: vietnam091945
      MYSQL_DATABASE: chemical_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - chemical_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    image: hoatran1002/chemical_app:v2
    container_name: chemical_app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - chemical_network

volumes:
  db_data:

networks:
  chemical_network:
    driver: bridge
